---
title: Better Data Cleaning Using R and the Tidyverse
author: Mark
date: '2020-09-19'
slug: better-data-cleaning-using-r-and-the-tidyverse
categories:
  - workshop
tags:
  - Data Cleaning
  - R
event: ~
event_url: ~
location: 'Delivered Virtually'
address:
  street: ~
  city: ~
  region: ~
  postcode: ~
  country: ~
summary: "Data cleaning workshop presented at the CPA 2020 Virtual Conference."
abstract: "Data cleaning is a time consuming and often error-prone process which every researcher will experience. It is said that 80% of data analysis time is spent on the process of cleaning and preparing the data (Dasu & Johnson, 2003), but this time spent cleaning and preparing data can be dramatically reduced by using the right tools/techniques for the job. The workshop will begin with a foundational discussion on data structures within R and general coding practices. The focus will then shift to the more practical topics of using a variety of packages to import/export data, inspect and manipulate specific types of data (including categorical, dates, and character type), reformat data, and produce quality graphics to showcase your data. A publicly available dataset will be used as a running example throughout the workshop to provide hands-on experience using each of the techniques discussed. Periodic interactive exercises will be presented to allow attendees an opportunity to work collaboratively to solve common data cleaning dilemmas. Attendees are encouraged to bring data from their own research to apply the techniques covered throughout the workshop."
date_end: '2020-09-19T21:34:27-04:00'
all_day: no
publishDate: '2020-09-19T21:34:27-04:00'
authors: [admin]
featured: yes
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_slides: ~
url_project: "https://github.com/Standard-Deviator/CPA_2020_data_cleaning_tidyverse"
url_pdf: ~
url_video: ~
slides: ~
projects: []
---


:::btn-group
<a class="btn btn-outline-primary my-1 mr-1" href="/workshop/CPA_2020_data_cleaning_tidyverse/slides/Section_1.html" target="_blank" rel="noopener">Section 1 Slides</a>


  <a class="btn btn-outline-primary my-1 mr-1" href="/workshop/CPA_2020_data_cleaning_tidyverse/slides/Section_2.html" target="_blank" rel="noopener">Section 2 Slides</a>

  <a class="btn btn-outline-primary my-1 mr-1" href="/workshop/CPA_2020_data_cleaning_tidyverse/slides/Section_3.html" target="_blank" rel="noopener">Section 3 Slides</a>
:::

This workshop was presented virtually at the 81st Canadian Psychological Association (CPA) Annual National Convention. It was broken down into three sections:

  1. Things to look for
  2. Tidy Data
  3. Profiling Missingness and Dates

Summary:  

Data cleaning is a time consuming and often error-prone process which every researcher will experience. It is said that 80% of data analysis time is spent on the process of cleaning and preparing the data (Dasu & Johnson, 2003), but this time spent cleaning and preparing data can be dramatically reduced by using the right tools/techniques for the job. The workshop will begin with a foundational discussion on data structures within R and general coding practices. The focus will then shift to the more practical topics of using a variety of packages to import/export data, inspect and manipulate specific types of data (including categorical, dates, and character type), reformat data, and produce quality graphics to showcase your data. A publicly available dataset will be used as a running example throughout the workshop to provide hands-on experience using each of the techniques discussed. Periodic interactive exercises will be presented to allow attendees an opportunity to work collaboratively to solve common data cleaning dilemmas. Attendees are encouraged to bring data from their own research to apply the techniques covered throughout the workshop.


**Adkins, M.C.**, & Cribbie, R. Better (and Quicker) Data Cleaning using R
and the Tidyverse. *Pre-Convention PD Workshop - Half Day. 81st Canadian
Psychological Association Annual National Convention*, Montréal, Quebec,
Canada.
